### ISSUE TITLE
Getting rid of outdated crate: `jemalloc-ctl`

### ISSUE THREAD

**Issue by powergee** [kaist-cp/smr-benchmark#44]
* 현재 상황
  * 메모리 할당 성능을 위해 기본 System allocator 대신 jemalloc을 이용하고 있음.
  * 이를 위해 두 crate를 사용하고 있는데,
    * `jemallocator`: jemalloc global allocator를 Rust로 래핑한 struct를 제공
    * `jemalloc-ctl`: jemalloc으로 할당된 메모리 사용량 등을 뽑기 위해 사용
* 문제
  * `jemalloc-ctl`은 개발이 중단되었고, `jemallocator`로 migrate되어 개발이 진행되고 있음.
  * HP++ 실험을 진행하던 Rust version에서는 문제가 없었으나, 최신 nightly version(nightly-2023-04-21)에서는 `future-incompatibilities` 경고가 발생함. (fs_extra v1.1.0는 jemalloc-ctl의 build-dependency)
```
warning: the following packages contain code that will be rejected by a future version of Rust: fs_extra v1.1.0
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
```
* 시도해볼 수 있는 해결 방법
  * `jemalloc-ctl`을 dependency에서 제거하고, `jemallocator`나 그 외 최신 crate을 통해 memory stat을 얻는 방법을 찾기.

**Comment by jeehoonkang** [comment]
제 생각에 시간이 오래 걸리진 않을 것 같은데 한번 시도해봐주실 수 있으실까요?

**Comment by powergee** [comment]
* `jemalloc-ctl`의 최신 successor로 `tikv-jemalloc-ctl`가 존재하는 것을 확인했습니다.
  * https://github.com/tikv/jemallocator/tree/main/jemalloc-ctl
* dependency를 `tikv-jemalloc-ctl`로 교체하여 빌드하니 warning없이 잘 빌드됨을 확인했습니다.
* 만약을 위해 이 상태로 memory consumption plot을 뽑아보고 이전의 경향성을 보여주는지 확인해보겠습니다.
